name: Debug

on: [push, workflow_dispatch]

env:
  XXX: asdsad

jobs:
  get-diff:
    runs-on: ubuntu-latest
    outputs:
      diff: ${{ steps.files.outputs.all }}
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - id: files
        uses: jitterbit/get-changed-files@v1
  
  debug:
    runs-on: ubuntu-latest
    steps:
      - name: Do work
        run: echo "Work done"
        if: ${{ contains(jobs.outputs.diff, '.github/workflows/debug.yml') }}
      - name: Run anyway
        run: |
          for changed_file in ${{ steps.files.outputs.all }}; do
            echo "${changed_file}"
          done
