name: Debug

on: 
  push:

jobs:
  test:
    runs-on: ubuntu-latest
    outputs:
      passed: ${{ env.RES != '0' }}
    steps:
      - name: Skip
        if: false
        run: echo "aboba"
        
  biba:
    runs-on: ubuntu-latest
    needs: test
    if: test.outputs.passed
    steps:
      - run: echo "DONE"
