name: Debug

on: 
  workflow_run:
    workflows: "Tag with SemVer"
    types:
      - completed
  workflow_dispatch:

jobs:
  debug:
    runs-on: ubuntu-latest
    steps:
      - run: echo "TAG=aboba" >> $GITHUB_ENV
      - run: echo $TAG
      
  job2:
    runs-on: ubuntu-latest
    steps:
      - run: echo $TAG
       
