name: Debug

on: 
  workflow_call:
    outputs:
      tag: 
        value: asdasd

jobs:
  tag:
    runs-on: ubuntu-latest
    outputs:
      tag: ${{ env.TAG }}
    steps:
      - name: Download artifact
        uses: dawidd6/action-download-artifact@v2
        with:
          run_id: ${{ github.event.workflow_run.id }}
          name: version-tag
          path: artifacts
      - name: Read
        run: echo "TAG=$(cat artifacts/version-tag)" >> $GITHUB_ENV
      - name: Tag
        run: echo $TAG
