name: Debug

on: 
  push:
  workflow_run:
    workflows: "Tag with SemVer"
    types:
      - completed

env:
  PATHS_REGEX: ^App1|debug.yml

jobs:
  get-diff:
    runs-on: ubuntu-latest
    outputs:
      has_diff: ${{ env.DIFF != '0' }}
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 2
      - name: Get diff files
        run: echo "DIFF=$(git diff HEAD HEAD^ --name-only | grep -cE '${{ env.PATHS_REGEX }}')" >> $GITHUB_ENV
      - run: echo "${{ env.DIFF }}"
  
  debug:
    runs-on: ubuntu-latest
    needs: get-diff
    env:
      DIFF: ${{ needs.get-diff.outputs.has_diff }}
    steps:
      - name: Do work
        run: echo "Work done"
        if: needs.get-diff.outputs.has_diff == true
      - name: Run anyway
        run: |
          for changed_file in $DIFF; do
            echo "${changed_file}"
          done
