name: Debug

on: 
  push:
    paths:
      - .github/workflows/debug.yml
  workflow_run:
    workflows: "Tag with SemVer"
    types:
      - completed
  workflow_dispatch:
    inputs:
      ignore_diff:
        description: Aba asda
        type: boolean
        default: true
env:
  PATHS_REGEX: ^App1|debug.yml

jobs:
  debug:
    runs-on: ubuntu-latest
    steps:
       - uses: actions/checkout@v3
         with:
            fetch-depth: 0

  print:
    runs-on: ubuntu-latest
    needs: debug
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - run: git tag -l | tail -n 1
