name: Debug

on: 
  push:

jobs:
  test:
    uses: Kamikoto-sama/GitVersionTest/.github/workflows/payload.yml@master
    with:
      value: aboba
      
  set-vars:
    runs-on: ubuntu-latest
    needs: test
    steps:
      - run: echo ${{ needs.test.outputs.value }}
