name: Debug

on: 
  push:
    paths:
      - .github/workflows/debug.yml
  workflow_run:
    workflows: "Tag with SemVer"
    types:
      - completed
  workflow_dispatch:
    inputs:
      fail:
        description: Fail
        type: boolean
        default: false

jobs:
  debug:
    runs-on: ubuntu-latest
    steps:
       - if: inputs.fail 
         run: |
          echo "Action failed"
          exit 1
