name: Debug

on: 
  push:

jobs:
  test:
    runs-on: ubuntu-latest
    outputs:
      passed: ${{ env.X != '0' }}
    steps:
      - uses: actions/script@master
        id: commits_count
        with:
          script: return context.payload.commits.length + 1
      - run: echo "${{ steps.commits_count.outputs.result }}"
      - uses: actions/checkout@v3
        with:
          fetch-depth: ${{ steps.commits_count.outputs.result }}
      - name: Get changed files
        id: changed-files
        uses: tj-actions/changed-files@v36
      - name: List all changed files
        run: |
          for file in ${{ steps.changed-files.outputs.all_changed_files }}; do
            echo "$file" >> diffs
          done
      - run: echo "X=$(grep -cE 'debug' diffs)" >> $GITHUB_ENV
      - run: echo "${{ env.ABOA != '0' }}"

  beta:
    runs-on: ubuntu-latest
    needs: test
    if: needs.test.outputs.passed == 'true'
    steps:
      - run: echo "${{ needs.test.outputs.passed }}"
