name: Debug

on: 
  push:

env:
  COUNT: 2

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          fetch-depth: env.COUNT
