name: Debug

on: 
  workflow_call:
    outputs:
      tag: ${{ jobs.debug.outputs }}

jobs:
  debug:
    runs-on: ubuntu-latest
    if: github.event.workflow_run.id
    outputs:
      tag: ${{ env.TAG }}
    steps:
      - name: Download artifact
        uses: dawidd6/action-download-artifact@v2
        with:
          run_id: ${{ github.event.workflow_run.id }}
          name: version-tag
          path: artifacts
      - name: Read
        run: echo "TAG=$(cat artifacts/version-tag)" >> $GITHUB_ENV
