name: Debug

on: 
  workflow_run:
    workflows: "Tag with SemVer"
    types:
      - completed
  workflow_dispatch:

jobs:
  debug:
    runs-on: ubuntu-latest
    steps:
      - run: echo "${{ env.AB != '0' }}"
