name: Debug

on: 
  workflow_call:
    outputs:
      tag:
        value: ${{ jobs.retag.outputs.tag }}

jobs:
  tag:
    if: github.event.workflow_run.id
    runs-on: ubuntu-latest
    outputs:
      tag: ${{ env.TAG }}
    steps:
      - name: Download artifact
        if: github.event.workflow_run.id
        uses: dawidd6/action-download-artifact@v2
        with:
          run_id: ${{ github.event.workflow_run.id }}
          name: version-tag
          path: artifacts
      - name: Read
        if: github.event.workflow_run.id
        run: echo "TAG=$(cat artifacts/version-tag)" >> $GITHUB_ENV
      - name: Default
        if: '!env.TAG'
        run: echo "TAG=123" >> $GITHUB_ENV
