name: Debug

on: [push, workflow_dispatch]

jobs:
  get-diff:
    runs-on: ubuntu-latest
    outputs:
      diff: ${{ steps.files.outputs.all }}
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - id: files
        uses: jitterbit/get-changed-files@v1
  
  debug:
    runs-on: ubuntu-latest
    needs: get-diff
    env:
      DIFF: ${{ needs.get-diff.outputs.diff }}
    steps:
      - name: Do work
        run: echo "Work done"
        if: ${{ contains(env.DIFF, '.github/workflows/debug.yml') }}
      - name: Run anyway
        run: |
          for changed_file in $DIFF; do
            echo "${changed_file}"
          done
