name: Debug

on: 
  workflow_call:
    outputs:
      tag: 
        value: aASDas8142

jobs:
  tag:
    if: github.event.workflow_run.id
    runs-on: ubuntu-latest
    outputs:
      tag: ${{ env.TAG }}
    steps:
      - run: echo ${{ github.event.workflow_run.id }}
      - name: Download artifact
        uses: dawidd6/action-download-artifact@v2
        with:
          run_id: ${{ github.event.workflow_run.id }}
          name: version-tag
          path: artifacts
      - name: Read
        run: echo "TAG=$(cat artifacts/version-tag)" >> $GITHUB_ENV
      - name: Tag
        run: echo $TAG
        
  retag:
    runs-on: ubuntu-latest
    steps:
      - run: echo "TAG=123" >> $GITHUB_ENV
