name: Debug

on: 
  push:

env:
  MANUAL_RUN: ${{ github.event_name == 'workflow_dispatch' }}

  DIFF_PATH_REGEX: ^Account/Account.Api

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - run: echo "${{ env.MANUAL_RUN }}"
