name: Debug

on: 
  workflow_run:
    workflows: "Tag with SemVer"
    types:
      - completed
  workflow_dispatch:
    inputs:
      fail:
        description: Fail
        type: boolean
        default: false

jobs:
  debug:
    runs-on: ubuntu-latest
    steps:
      - name: 'Download artifact'
        uses: actions/github-script@v6
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          script: |
            const artifactsInfo = await github.rest.actions.listWorkflowRunArtifacts({
            owner: context.repo.owner,
            repo: context.repo.repo,
            run_id: context.payload.workflow_run.id,
            });

            console.log(artifactsInfo);

            const matchArtifact = artifactsInfo.data.artifacts.filter((artifact) => {
             return artifact.name == "version-tag"
            })[0];

            const download = await github.rest.actions.downloadArtifact({
              owner: context.repo.owner,
              repo: context.repo.repo,
              artifact_id: matchArtifact.id,
            });
            const fs = require('fs');
            fs.writeFileSync(`version-tag`, Buffer.from(download.data));
      - name: Display version
        run: cat version-tag
