name: Debug

on: 
  workflow_run:
    workflows: "Tag with SemVer"
    types:
      - completed
  workflow_dispatch:

jobs:
  debug:
    runs-on: ubuntu-latest
    steps:
      - name: Download artifact
        id: download-artifact
        uses: dawidd6/action-download-artifact@v2
        with:
          run_id: ${{ github.event.workflow_run.id }}
          name: version-tag
          path: artifacts
      - name: Echo
        run: cat artifacts/version-tag
