name: Do work

on:
  workflow_run:
    workflows: "Tag with SemVer"
    types:
      - completed
  workflow_dispatch:
  workflow_call:
    inputs:
      value:
        type: string
        required: true
    outputs:
      value: ${{ jobs.do-work.outputs.value }}

jobs:
  do-work:
    runs-on: ubuntu-latest
    outputs:
      value: ${{ env.VER }}
    steps:
      - run: echo "VER=${{ inputs.value }}" >> $GITHUB_ENV
      - run: echo $VER
