name: Do work

on:
  workflow_run:
    workflows: "Tag with SemVer"
    types:
      - completed
      
jobs:
  get-tag:
    runs-on: ubuntu-latest
    outputs:
      tag: ${{ env.TAG }}
    steps:
       - uses: actions/checkout@v3
         with:
            fetch-depth: 0
       - run: git tag --contains ${{ github.sha }}
       - name: Set tag to env
         run: echo "TAG=$(git tag --contains ${{ github.sha }})" >> $GITHUB_ENV
       - name: Print tag
         run: echo $TAG
         
  do-work:
    runs-on: ubuntu-latest
    needs: get-tag
    if: needs.get-tag.outputs.tag != ''
    env:
      VER: ${{ needs.get-tag.outputs.tag }}
    steps:
    - name: Work
      run: echo $VER
       
