name: Do work

on:
  workflow_run:
    workflows: "Tag with SemVer"
    types:
      - completed
  workflow_dispatch:
  workflow_call:
    inputs:
      value:
        type: string
        required: true

jobs:
  do-work:
    runs-on: ubuntu-latest
    steps:
      - run: echo "${{ inputs.value }}"
