name: Do work

on:
  workflow_run:
    workflows: "Tag with SemVer"
    types:
      - completed
  workflow_dispatch:

jobs:
  get-tag:
    uses: Kamikoto-sama/GitVersionTest/.github/workflows/debug.yml@master
    
  do-work:
    runs-on: ubuntu-latest
    needs: get-tag
    steps:
      - run: echo ${{ needs.outputs.tag }}
