name: Tag

on:
  push:
    branches: master
    tags-ignore: "**"
  workflow_dispatch:

permissions:
  contents: write

jobs:
  build-tag:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - uses: gittools/actions/gitversion/setup@main
        with:
          versionSpec: '5.x'
      - id: gitversion
        uses: gittools/actions/gitversion/execute@main
        with:
          useConfigFile: true
          configFilePath: .github/GitVersionConf.yml
      - name: Display SemVer
        run: echo "${{ steps.gitversion.outputs.semVer }}"
