name: Tag with SemVer

on:
  push:
    branches: master
    tags-ignore: "**"

permissions:
  contents: write

jobs:
  build-tag:
    runs-on: ubuntu-latest
    steps:
      - name: Event name
        run: echo "${{ github.event_name }}"
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - uses: gittools/actions/gitversion/setup@main
        with:
          versionSpec: '5.x'
      - id: gitversion
        uses: gittools/actions/gitversion/execute@main
        with:
          useConfigFile: true
          configFilePath: .github/GitVersionConf.yml
      - name: Display SemVer
        run: echo "${{ steps.gitversion.outputs.semVer }}"
      - uses: actions/github-script@v6
        with:
          script: |
            github.rest.git.createRef({
              owner: context.repo.owner,
              repo: context.repo.repo,
              ref: 'refs/tags/${{ steps.gitversion.outputs.semVer }}',
              sha: context.sha
            })
