name: Tag

on:
  push:

permissions:
  contents: write
  
jobs:
  tag:
    name: Tag
    runs-on: ubuntu-latest
    steps:
      - id: ver
        uses: GitVersionTest/.github/workflows/build-version@master
      - run: echo "${{ steps.ver.outputs.semVer }}"
#       - uses: rickstaa/action-create-tag@v1 
#         with:
#          tag: ${{ steps.ver.outputs.semVer }}
