name: Tag

on:
  push:

permissions:
  contents: write
  
jobs:
  ver:
    uses: Kamikoto-sama/GitVersionTest/.github/workflows/build-version.yml@master

  tag:
    name: Tag
    runs-on: ubuntu-latest
    needs: ver
    steps:
      - run: echo "${{ needs.ver.outputs.semVer }}"
#       - uses: rickstaa/action-create-tag@v1 
#         with:
#          tag: ${{ steps.ver.outputs.semVer }}
