name: Tag

on:
  push:

permissions:
  contents: write
  
jobs:
  ver:
    uses: Kamikoto-sama/GitVersionTest/.github/workflows/build-version.yml@master

  tag:
    name: Tag
    runs-on: ubuntu-latest
    needs: ver
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - uses: rickstaa/action-create-tag@v1 
        with:
         tag: ${{ needs.ver.outputs.semVer }}
