name: Test

on:
  workflow_dispatch:
  push:
    branches:
    - master

permissions:
  contents: write

jobs:
  test:
    name: Job name
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - uses: gittools/actions/gitversion/setup@main
        with:
          versionSpec: '5.x'
      - name: Compute SemVer
        id: ver
        uses: gittools/actions/gitversion/execute@main
        with:
          useConfigFile: true
          configFilePath: .github/GitVersionConf.yml
      - name: Display SemVer
        run: echo "${{ steps.ver.outputs.semVer }}"
      - uses: rickstaa/action-create-tag@v1
        id: "tag_create"
        with:
          tag: ${{ steps.ver.outputs.semVer }}
          tag_exists_error: true
          message: ${{ steps.ver.outputs.semVer }}

      # Print result using the env variable.
      -  run: |
          echo "Tag already present: ${{ env.TAG_EXISTS }}"

      # Print result using the action output.
      - run: |
          echo "Tag already present: ${{ steps.tag_create.outputs.tag_exists }}"
